ALTER TABLE users ADD COLUMN provider VARCHAR DEFAULT NULL;
ALTER TABLE users ADD COLUMN provider_user_id VARCHAR DEFAULT NULL;
ALTER TABLE users ADD COLUMN provider_email VARCHAR DEFAULT NULL;
ALTER TABLE users ADD COLUMN provider_data VARCHAR DEFAULT NULL;
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ALTER COLUMN hashed_password DROP NOT NULL;